<<<<<<< HEAD
# Generated by Django 3.2 on 2021-05-10 13:54
=======
# Generated by Django 3.2 on 2021-05-06 12:23

>>>>>>> 7c459b18d0a8d68ee5c8df38e635dca1c3b2b86c

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('script', models.TextField()),
                ('keyword', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
=======
>>>>>>> 7c459b18d0a8d68ee5c8df38e635dca1c3b2b86c
                ('title', models.CharField(max_length=50)),
                ('topic', models.TextField()),
                ('writer', models.CharField(max_length=30)),
                ('parties', models.TextField()),
                ('meeting_date', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='', verbose_name='media/')),
<<<<<<< HEAD
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo/')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='testapp.result')),
=======
>>>>>>> 7c459b18d0a8d68ee5c8df38e635dca1c3b2b86c
            ],
        ),
    ]
