# Generated by Django 3.2 on 2021-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='file',
            field=models.FileField(upload_to='', verbose_name='media/'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='writer',
            field=models.CharField(max_length=30),
        ),
    ]
