# Generated by Django 3.2 on 2021-07-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
