# Generated by Django 3.2 on 2021-06-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
        ('testapp', '0003_result'),
    ]

    operations = [
    ]
